# Dropbox API credentials and refresh token configuration
[dropbox]
client_id = 'rat7kla7ccs5jlh'
client_secret = 'nxllirlz2gkyfcp'
refresh_token = 'FQRGITyZPF8AAAAAAAAAAVqWZsc3kexKorfdFaXx7-qu0JV0OGfX9wHZQL1WaMO1'

[auth]
password = 'lincoln wins award season'

[name]
name1 = 'Khadijia Bulli'
name2 = 'Marcos Mendez'

[cookie_auth]
